name: Backend CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: PIP INSTALL
        run: pip install pipenv

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
        
      - name: INSTALL DEPENDENCIES
        run: |
          pipenv install --dev
          pipenv install flake8
          
      - name: Run Code Convention
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: PIP INSTALL
        run: pip install pipenv

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}

      - name: INSTALL DEPENDENCIES
        run: |
          pipenv install --dev
          pipenv install flake8
  
      - name: RUN TESTS
        run: pipenv run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint,test]
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build .
